# Generated by Django 6.0.1 on 2026-01-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.TextField()),
                ('short_code', models.CharField(db_index=True, max_length=7, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('click_count', models.BigIntegerField(default=0)),
            ],
        ),
    ]
