# Generated by Django 6.0.1 on 2026-02-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='short_code',
            field=models.CharField(db_index=True, max_length=6, unique=True),
        ),
    ]
